// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoCLiRb7HCNEnQsZPft48jjo8POdao6n0',
    appId: '1:141531322990:web:466d71a494a24da35d647f',
    messagingSenderId: '141531322990',
    projectId: 'recipe-app-739e6',
    authDomain: 'recipe-app-739e6.firebaseapp.com',
    storageBucket: 'recipe-app-739e6.appspot.com',
    measurementId: 'G-RYT2525QGS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3Ks1aFN2oMBzpFd3kum8-ru3UgDrg0TM',
    appId: '1:141531322990:android:3f9aff4a054fb6e25d647f',
    messagingSenderId: '141531322990',
    projectId: 'recipe-app-739e6',
    storageBucket: 'recipe-app-739e6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQnd3KXll1NfA8EPightGdTj4vOeX_osM',
    appId: '1:141531322990:ios:727ca7367aa05cfc5d647f',
    messagingSenderId: '141531322990',
    projectId: 'recipe-app-739e6',
    storageBucket: 'recipe-app-739e6.appspot.com',
    iosBundleId: 'com.example.recipeapp',
  );
}
